### ISSUE TITLE
Migrate to Vite + TypeScript

### ISSUE THREAD

**Issue by mithintv** [mithintv/dev-portfolio#27]
#### Tasks
- [ ] Instantiate new Vite project w/ TypeScript
- [ ] Port existing JS code to TS
- [ ] Test basic functionality
